export const DEFAULT_BALANCE_CATEGORIES = [
  {
    name: "Здоровье",
    slug: "health",
    color: "#F0A43A",
    icon: "activity",
    targetMinutesPerWeek: 300,
    sortOrder: 0,
  },
  {
    name: "Карьера",
    slug: "career",
    color: "#D88A2D",
    icon: "briefcase-business",
    targetMinutesPerWeek: 600,
    sortOrder: 1,
  },
  {
    name: "Отношения",
    slug: "relationships",
    color: "#F1D39A",
    icon: "users",
    targetMinutesPerWeek: 240,
    sortOrder: 2,
  },
  {
    name: "Развитие",
    slug: "growth",
    color: "#E5B963",
    icon: "book-open",
    targetMinutesPerWeek: 300,
    sortOrder: 3,
  },
  {
    name: "Финансы",
    slug: "finance",
    color: "#B97831",
    icon: "wallet-cards",
    targetMinutesPerWeek: 120,
    sortOrder: 4,
  },
  {
    name: "Отдых",
    slug: "rest",
    color: "#E8D7B0",
    icon: "moon-star",
    targetMinutesPerWeek: 420,
    sortOrder: 5,
  },
  {
    name: "Творчество",
    slug: "creativity",
    color: "#C88A3D",
    icon: "palette",
    targetMinutesPerWeek: 180,
    sortOrder: 6,
  },
  {
    name: "Окружение",
    slug: "environment",
    color: "#D6D0C5",
    icon: "house",
    targetMinutesPerWeek: 180,
    sortOrder: 7,
  },
] as const;
